### ISSUE TITLE
Allow the user to specify a ref on the command line

### ISSUE THREAD

**Issue by drewdeponte** [uptech/git-changelog#3]
Instead of using HEAD all the time we should allow the user to specify ref on the command line and use that instead of HEAD. Or possibly a start ref and an end ref so they could limit the range of commits that are processed.

**Comment by drewdeponte** [comment]
doing this with two refs should be pretty straight forward

see `public func commits(from fromRef: String, to toRef: String) throws -> [CommitSummary]` in `GitShell.swift` for an example.

**Comment by drewdeponte** [comment]
I think there should probably be the following variations of command line arguments to support:
```
git-changelog [start-ref [stop-ref]]

git-changelog start-ref # this would go from start-ref to the end
git-changelog start-ref stop-ref # this would go from start-ref to stop-ref
```

**Comment by anthonycastelli** [comment]
#7 Closes this
